Tarea028 sprint2#55
alejandromd/Acme-L3-D01 pull request #80
Opened 2023-02-22 18:00 UTC by Thealean28

2023-02-23 21:16 UTC, goncammej requested changes

2023-02-23 21:16 UTC, goncammej commented on src/main/java/acme/entities/Peep.java
> +	protected String			email;
Añadir constraint "@Email"

2023-02-26 17:51 UTC, goncammej requested changes

2023-02-26 17:51 UTC, goncammej commented on src/main/java/acme/entities/Peep.java
> +	protected Date				instantiationMoment;
Añadir constraint "@Temporal(spec = TIMESTAMP)" y "@NotNull"

2023-03-02 12:16 UTC, Thealean28 commented
Todo corregido

2023-03-02 12:24 UTC, goncammej approved these changes
Todo correcto.

2023-03-02 12:25 UTC, merged